global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mev-burn-indexer'

scrape_configs:
  - job_name: 'mev-burn-indexer'
    static_configs:
      - targets: ['172.17.0.1:9091']
        labels:
          service: 'mev-burn-indexer'
          environment: 'production'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
